version: '3.7'
services:
  dynamic-readme-prod:
    container_name: dr-prod-app
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    command: npm run start:prod
    ports:
      - ${DOCKER_LOCAL_PORT}:${APP_PORT}
    networks:
      - app-network-prod
    volumes:
      - ./config.json:/usr/src/app/config.json
    depends_on:
      - redis-prod
  redis-prod:
    container_name: dr-prod-redis
    restart: unless-stopped
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data-prod:/data
    networks:
      - app-network-prod

volumes:
  redis-data-prod:
networks:
  app-network-prod: