version: '3.7'
services:
  dynamic-readme-prod:
    container_name: dr-prod-app
    restart: unless-stopped
    image: charleschrismann/dynamic-readme:latest
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    command: npm run start:prod
    ports:
      - 3000:${EC2_PORT}
    networks:
      - app-network-prod
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
  redis-prod:
    container_name: dr-prod-redis
    restart: unless-stopped
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data-prod:/data
    networks:
      - app-network-prod

volumes:
  redis-data-prod:
networks:
  app-network-prod: